### ISSUE TITLE
An error when run 4dface app

### ISSUE THREAD

**Issue by ZhaozhengPlus** [patrikhuber/4dface#1]
I did the steps as you say in readme.md , and my system is ubuntu 14.04 , but when I run the 4dface app ,it occurs **## "terminate called after throwing an instance of 'std::runtime_error' what():  Error opening given file: ../share/sfm_shape_3448.bin
已放弃 (核心已转储)"**

How can I solve the problem ?

**Comment by patrikhuber** [comment]
The error says that the file `../share/sfm_shape_3448.bin` couldn't be found. I think you most likely didn't run the `install` target. It copies the model files to the install directory, so they will be automatically found by the executable. Either run the `install` target, or just specify the model file with `-m path-to-model` - you probably also need to specify all the other files needed, so running the `install` target would be easier since it copies everything to the correct place.

**Comment by patrikhuber** [comment]
I'll close this, since it was simply a matter of not passing the correct path to the model file on the command-line.
