### ISSUE TITLE
How can I use my own set of 2D landmarks in eos

### ISSUE THREAD

**Issue by che454** [patrikhuber/4dface#13]
Dear Patrik,

Thanks for your great working, which is very helpful for my research.
I want to try use another set of 2D landmarks(72 landmarks), which I manually labeled the corresponding vertex on the PCA model, and change ibug2did.txt for remapping. I found that the results of the testing is wrong. How can I use my own set of 2D landmarks in eos?

Best Regards
Che #

**Comment by patrikhuber** [comment]
Hi Che,

Thanks very much! :-)
What you've done so far sounds pretty much correct. I think you probably got something wrong with respect to the contour landmarks. Maybe try fitting without any contours (see the `fit-model-simple` example) - if that doesn't work, you've made a trivial error. If that works, but not `fit-model`, then you've probably made a mistake with the contour definitions.

Cheers,
Patrik

**Comment by che454** [comment]
Hi Patrik，

First,Merry Christmas^^

I have solved the problem. As you said, I confused contourof the left and right-_-

Anyway,it works perfectly now.

By the way, may I get the the HD "16759" and "29587" model and blendshape、edge topology binary files? 

I registered in "http://cvssp.org/faceweb/3dmm/facemodels/register.html", but there has been no reply.

Thank you very much!

Best Regards
Che

**Comment by patrikhuber** [comment]
Thank you, Merry Christmas too ;-)

Great! Hmm you raise a good point, I don't think it's described anywhere what "right" and "left" mean - people coming from the 2D world usually think that e.g. "left contour" is the one on the left side of an image, while in the 3D world things are usually described from the persons (or models) perspective, because it's unambiguous. We should document that somewhere more clearly :-)

Regarding the high-res models, this goes through the University, and everyone there will be on leave until 3rd January, so you can't expect a reply before the 6th or possibly even the week after. You can write them an email to try to speed it up to get it at least in the week of the 3rd. Is that OK for you?

Thanks for your interest :-)

**Comment by che454** [comment]
Thank you very much!
I learned a lot about regression and 3D's algorithms from your project!
Thanks again!
Have a nice day :)
