### ISSUE TITLE
Face Fine Details Fitting

### ISSUE THREAD

**Issue by DannyJieweiLi** [patrikhuber/4dface#30]
I noticed that the fitting module of eos only contains code of fitting landmarks (related to function fitting::fit_shape_and_pose).  The result 3D model is smooth and do not have much details. Is there any way to improve the details (i.e wrinkles) of the result model? 
I thought that the detail missing is caused by the low resolution of morphable model (3448 vertices model). But even I used the higher resolution model, I do not get the expected details.

**Comment by patrikhuber** [comment]
Hi Danny,

Thanks for your comment!

Yes, all your observations are correct. The high resolution model would not help much since it's doing landmarks-fitting. Here's two things:

1) You can build something on top of eos - i.e. use the result of the landmark fitting to do some more precise fitting, e.g. analysis-by-synthesis, Shape-from-Shading, or something like that. There's a ton of literature about it.

2) I have plans to improve the fitting of eos, and will work on that over the next months. However there will nothing be ready soon, and it will definitely take a few months, and I cannot promise any results at this point.

**Comment by DannyJieweiLi** [comment]
Thanks your reply, Patrick. I will look into the detail keeping algorithms. ^_^

**Comment by sunjunlishi** [comment]
great,author!

**Comment by patrikhuber** [comment]
Great, I will close it in the mean time. I will update it when I make some improvements to the fitting algorithm. It's also worth following the releases of [eos](github.com/patrikhuber/eos). Also feel free to update this issue if you implement something! :-)
Thanks!
